Repository haerxeong/kickon-frontend, pull requests merged in 2025-04, with the labels that each got.

#28 Feat: 클럽 커뮤니티 게시글 리스트 컴포넌트 개발
  kickon-fe/package.json
  kickon-fe/src/assets/good.png
  kickon-fe/src/assets/image.svg
  kickon-fe/src/assets/more.png
  kickon-fe/src/assets/profile.svg
  kickon-fe/src/components/CommunityBoard/CommunityBoard.style.js
  kickon-fe/src/components/CommunityBoard/communityBoard.jsx
  kickon-fe/src/components/MainBanner/mainBanner.style.js
  kickon-fe/src/components/Profile/profile.style.js
  kickon-fe/src/components/RankingTable/rankingTable.style.js
  kickon-fe/src/index.css
  kickon-fe/src/layout/root-layout.jsx
  kickon-fe/src/pages/Home/home.jsx
  kickon-fe/yarn.lock
Labels: :sparkles: feature

#31 Feat: 글 작성 컴포넌트 구현
  kickon-fe/src/App.jsx
  kickon-fe/src/components/PostEditer/postEditor.jsx
  kickon-fe/src/components/PostEditer/postEditor.style.js
  kickon-fe/src/layout/root-layout.jsx
Labels: :sparkles: feature

#26 Feat: 탑 뉴스 컴포넌트 제작
  kickon-fe/src/assets/news_image.png
  kickon-fe/src/components/MatchCard/matchCard.style.js
  kickon-fe/src/components/TopNews/topNews.jsx
  kickon-fe/src/components/TopNews/topNews.style.js
  kickon-fe/src/layout/root-layout.jsx
Labels: :sparkles: feature

#38 Feat: 뉴스 상세화면, 커뮤니티 상세화면 구분
  kickon-fe/package.json
  kickon-fe/src/components/PostDetail/postDetail.jsx
  kickon-fe/src/components/PostDetail/postDetail.style.js
  kickon-fe/yarn.lock
Labels: :sparkles: feature

#40 Chore: update PR template from main
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :bug: bug

#41 Feat: 뉴스 메인 페이지 제작
  kickon-fe/src/components/NewsList/NewsItem.jsx
  kickon-fe/src/components/NewsList/NewsItem.style.js
  kickon-fe/src/components/NewsList/NewsList.style.js
  kickon-fe/src/components/NewsList/newsList.jsx
  kickon-fe/src/components/RankingTable/rankingTable.jsx
  kickon-fe/src/components/RankingTable/rankingTable.style.js
  kickon-fe/src/layout/root-layout.jsx
  kickon-fe/src/mocks/newsList.js
  kickon-fe/src/mocks/rankings.js
  kickon-fe/src/pages/Home/home.jsx
  kickon-fe/src/pages/Home/home.style.js
  kickon-fe/src/pages/News/news.jsx
  kickon-fe/src/pages/News/news.style.js
  kickon-fe/src/utils/timeUtils.js
Labels: :sparkles: feature

#42 Refactor: 프로필 컴포넌트 수정
  kickon-fe/src/components/Profile/profile.jsx
  kickon-fe/src/components/Profile/profile.style.js
Labels: :recycle: refactor

#46 Refactor: rankingTable, header 디자인 수정
  kickon-fe/src/components/Header/header.jsx
  kickon-fe/src/components/Header/header.style.js
  kickon-fe/src/components/RankingTable/rankingTable.jsx
  kickon-fe/src/components/RankingTable/rankingTable.style.js
  kickon-fe/src/layout/root-layout.jsx
Labels: :recycle: refactor

#44 Refactor: 승부예측 컴포넌트 UI 개선
  kickon-fe/src/components/MatchCard/matchCard.jsx
  kickon-fe/src/components/MatchCard/matchCard.style.js
Labels: :recycle: refactor

#47 Feat: 답글 UI 구현
  kickon-fe/package.json
  kickon-fe/src/assets/report.svg
  kickon-fe/src/components/PostDetail/postDetail.jsx
  kickon-fe/src/components/PostDetail/postDetail.style.js
  kickon-fe/yarn.lock
Labels: :sparkles: feature

#58 Feat: 신고 UI 구현
  kickon-fe/src/apis/axios-instance.js
  src/App.jsx
  src/components/PostDetail/postDetail.jsx
  src/components/ReportModal/reportModal.jsx
  src/components/ReportModal/reportModal.style.js
  src/features/modal/modalSlice.js
  src/store/store.js
Labels: :sparkles: feature

#62 Refactor: 회원가입 페이지 디자인 리팩토링
  src/components/Header/header.style.js
  src/pages/Signup/signup.jsx
  src/pages/Signup/signup.style.js
Labels: :recycle: refactor

#63 Feat: 상세페이지 함께 볼 리스트 추가
  src/App.jsx
  src/components/CommunityBoard/communityBoard.jsx
  src/components/NewsList/newsList.jsx
  src/pages/Community/communityDetail.jsx
  src/pages/News/newsDetail.jsx
Labels: :sparkles: feature

#66 Feat: 소셜 로그인 API 연결
  src/App.jsx
  src/apis/domains/auth/updatePrivacyAgreement.js
  src/apis/domains/auth/updateUserInfo.js
  src/apis/domains/common/getLeagues.js
  src/apis/domains/common/getTeams.js
  src/components/LoginModal/loginModal.jsx
  src/context/AuthContext.jsx
  src/pages/Signup/signup.jsx
  src/pages/Signup/signup.style.js
Labels: :sparkles: feature

#68 Feat: 커뮤니티 게시글 리스트 조회
  package.json
  src/App.jsx
  src/apis/domains/community/getBoardList.js
  src/components/Pagination/pagination.style.js
  src/pages/Community/community.jsx
  src/pages/Community/community.style.js
  src/pages/Signup/signup.jsx
  src/store/useLeagueTeamStore.js
  yarn.lock
Labels: :sparkles: feature

#69 Feat: 뉴스 리스트 조회 API 연결
  src/App.jsx
  src/apis/domains/news/getNewsList.js
  src/components/League/leagueDropdown.jsx
  src/components/League/leagueDropdown.style.js
  src/pages/Community/community.jsx
  src/pages/News/NewsItem.jsx
  src/pages/News/NewsItem.style.js
  src/pages/News/news.jsx
  src/pages/News/news.style.js
  src/pages/Signup/signup.jsx
  src/utils/textUtils.js
Labels: :sparkles: feature

#73 Feat: 매치 리스트 api 연결
  src/apis/domains/common/getMatchList.js
  src/components/MatchCard/matchCard.jsx
  src/components/MatchCard/matchCard.style.js
Labels: :sparkles: feature

#75 feat: 탑 뉴스 api 연결
  src/apis/domains/news/getTopNews.js
  src/components/MatchCard/matchCard.jsx
  src/components/TopNews/topNews.jsx
  src/components/TopNews/topNews.style.js
Labels: :sparkles: feature

#76 feat:뉴스, 게시판 상세보기 API 연결
  package.json
  src/App.jsx
  src/apis/domains/community/community.js
  src/apis/domains/news/news.js
  src/components/PostDetail/postDetail.jsx
  yarn.lock
Labels: :sparkles: feature

#81 Feat: 게시글/뉴스 뷰 생성 API 연결
  src/pages/Community/community.jsx
  src/pages/News/NewsItem.jsx
Labels: :sparkles: feature

#90 Feat: 승부예측 생성 및 수정 api 연결
  src/apis/domains/common/patchGamble.js
  src/apis/domains/common/postGamble.js
  src/components/MatchCard/matchCard.jsx
  src/components/MatchCard/matchCard.style.js
Labels: :sparkles: feature, fix
