Repository haerxeong/kickon-frontend, pull requests merged in 2025-06, with the labels that each got.

#140 Feat: 이적 예측에 로그인 모달 추가
  src/pages/Transferability/transferability.jsx
Labels: :sparkles: feature

#141 Refactor: 이미지 관련 기능 수정
  src/apis/domains/auth/updateUserInfo.js
  src/pages/ProfileSettings/ProfileSettings.jsx
  src/utils/imageUpload.js
Labels: :recycle: refactor

#144 Feat: 중고거래 리스트/상세페이지 API 연결
  src/App.jsx
  src/apis/domains/market/getItemDetail.js
  src/apis/domains/market/getItemList.js
  src/layout/root-layout.jsx
  src/pages/Market/market.jsx
  src/pages/Market/marketDetail.jsx
  src/pages/Market/marketDetail.style.js
Labels: :sparkles: feature

#162 Fix: 전체로 글쓰기 수정
  src/components/PostDetail/postDetail.jsx
  src/components/PostEditer/postEditor.jsx
Labels: :bug: bug

#163 Refactor: 리드미 수정
  README.md
Labels: :recycle: refactor

#171 Feat: 검색창 및 카테고리 정렬 추가
  package.json
  src/pages/Market/market.jsx
  src/pages/Market/market.style.js
  yarn.lock
Labels: :sparkles: feature

#173 Fix: 게시글 오류 해결
  src/components/PostDetail/postDetail.jsx
  src/components/PostEditer/postEditor.jsx
Labels: :bug: bug

#174 Fix: 게시글 상세/에디터 수정
  src/components/PostDetail/postDetail.jsx
  src/components/PostEditer/postEditor.jsx
  src/pages/Market/marketDetail.jsx
Labels: :bug: bug

#176 Feat: 약관 보기 클릭
  src/pages/Signup/signup.jsx
Labels: :recycle: refactor

#178 Refactor: 숏츠도 재생되게 수정
  src/components/PostDetail/postDetail.jsx
Labels: :recycle: refactor
