Repository haerxeong/kickon-frontend, pull requests merged in 2025-05, with the labels that each got.

#82 승부예측/실제 시즌 랭킹 리스트 조회 & 뉴스/게시글 신고 생성/공유하기 & 상세보기 이미지 표시 문제 수정
  src/apis/domains/ranking/ranking.js
  src/apis/domains/report/report.js
  src/components/PostDetail/postDetail.jsx
  src/components/PostDetail/postDetail.style.js
  src/components/RankingTable/rankingTable.jsx
  src/components/ReportModal/reportModal.jsx
  src/features/modal/modalSlice.js
  src/layout/root-layout.jsx
Labels: :sparkles: feature, fix

#92 Feat: 댓글 관련 api 연결
  src/apis/domains/community/getCommunityCommentList.js
  src/apis/domains/news/getNewsCommentList.js
  src/components/PostDetail/postDetail.jsx
  src/components/PostDetail/postDetail.style.js
Labels: :sparkles: feature

#96 Refactor: 상태 관련 문제 해결
  src/apis/domains/auth/fetchUserInfo.js
  src/context/AuthContext.jsx
  src/pages/News/news.jsx
  src/pages/Signup/signup.jsx
  src/store/useLeagueTeamStore.js
Labels: :recycle: refactor

#100 Refactor: 태그 보이는 문제 해결
  src/pages/News/NewsItem.jsx
  src/utils/stripHtml.js
Labels: :recycle: refactor

#104 Feat: 데이터 없음 UI 구현 및 예외처리
  src/App.jsx
  src/assets/xCard.svg
  src/components/NoData/noData.jsx
  src/components/NoData/noData.style.js
  src/components/PostDetail/postDetail.jsx
  src/components/RankingTable/rankingTable.jsx
  src/components/TopNews/topNews.jsx
  src/components/TopNews/topNews.style.js
  src/pages/Community/community.jsx
  src/pages/Community/community.style.js
  src/pages/News/NewsItem.style.js
  src/pages/News/news.jsx
  src/pages/News/news.style.js
  src/pages/Transferability/transferability.jsx
  src/pages/not-found.jsx
  src/pages/notFound.jsx
  src/utils/newsCategoryMap.js
Labels: :recycle: refactor

#103 Refactor: 탑 뉴스 클릭이벤트 및 게시글 리스트 UI 개선
  src/components/CommunityBoard/CommunityBoard.style.js
  src/components/CommunityBoard/communityBoard.jsx
  src/components/NewsList/NewsItem.jsx
  src/components/NewsList/newsList.jsx
  src/components/Profile/profile.style.js
  src/components/TopNews/topNews.jsx
  src/pages/Community/community.jsx
  src/pages/Community/community.style.js
  src/pages/News/news.jsx
  src/pages/News/news.style.js
  src/pages/ProfileSettings/ProfileSettings.jsx
  src/utils/formatDate.js
Labels: :recycle: refactor

#107 Feat: 답글 api 연결
  src/components/Comment/comment.jsx
  src/components/Comment/comment.style.js
  src/components/PostDetail/postDetail.jsx
  src/components/PostDetail/postDetail.style.js
Labels: :sparkles: feature

#112 Feat: 배포환경에 맞춰 redirect url 수정
  src/components/LoginModal/loginModal.jsx
Labels: :sparkles: feature

#115 Refactor: 페이지 아이콘과 명 변경
  index.html
Labels: :recycle: refactor

#119 Feat: 테스트 후 수정
  src/components/CommunityBoard/communityBoard.jsx
  src/components/NewsList/NewsItem.jsx
  src/components/PostEditer/myQuill.jsx
  src/components/PostEditer/postEditor.jsx
  src/components/PostEditer/postEditor.style.js
  src/pages/Community/community.jsx
  src/pages/News/NewsItem.jsx
  src/pages/Signup/signup.jsx
  src/pages/Signup/signup.style.js
  src/utils/increaseViewCount.js
Labels: :sparkles: feature

#123 Feat: 테스트 후 수정
  src/apis/axios-instance.js
  src/apis/domains/common/getProfilecard.js
  src/apis/domains/common/getUserRanking.js
  src/components/PostDetail/postDetail.jsx
  src/components/PostEditer/postEditor.jsx
  src/components/Profile/profile.jsx
  src/components/WriteButton/writeButton.jsx
  src/context/AuthContext.jsx
  src/hooks/useAuthGuard.js
  src/layout/root-layout.jsx
  src/pages/News/news.jsx
  src/pages/Signup/signup.jsx
  src/pages/Transferability/transferability.jsx
  vite.config.js
Labels: :sparkles: feature

#122 Feat: 로딩스피너 적용 & 시차 계산
  src/components/Comment/comment.jsx
  src/components/CommunityBoard/communityBoard.jsx
  src/components/Header/header.style.js
  src/components/LoadingSpinner/loadingSpinner.jsx
  src/components/LoadingSpinner/loadingSpinner.style.js
  src/components/MatchCard/matchCard.jsx
  src/components/NewsList/newsList.jsx
  src/components/PostDetail/postDetail.jsx
  src/components/Profile/profile.jsx
  src/components/RankingTable/rankingTable.jsx
  src/components/TopNews/topNews.jsx
  src/components/TopNews/topNews.style.js
  src/layout/root-layout.jsx
  src/pages/ProfileSettings/ProfileSettings.jsx
  src/utils/formatDate.js
  src/utils/timeUtils.js
Labels: :sparkles: feature

#124 Bug: 파일 경로 수정
  src/components/LoadingSpinner/loadingSpinner.jsx
Labels: :sparkles: feature

#129 Fix: 커뮤니티도 같은 팀만 댓글
  src/components/Comment/comment.jsx
Labels: fix

#130 Feat: 승부예측랭킹 설명 추가
  src/components/RankingTable/rankingTable.jsx
  src/components/RankingTable/rankingTable.style.js
Labels: :sparkles: feature

#135 Feat: 중고거래 페이지 UI 제작
  src/App.jsx
  src/components/Header/header.jsx
  src/components/Header/header.style.js
  src/pages/Market/market.jsx
  src/pages/Market/market.style.js
Labels: :sparkles: feature
