Repository haerxeong/kickon-frontend, pull requests merged in 2025-03, with the labels that each got.

#7 Feat: 순위 테이블 컴포넌트 생성
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor.md
  kickon-fe/src/assets/sample_img.png
  kickon-fe/src/components/MatchCard/matchCard.jsx
  kickon-fe/src/components/NewsList/newsList.jsx
  kickon-fe/src/components/RankingTable/rankingTable.jsx
  kickon-fe/src/components/RankingTable/rankingTable.style.js
  kickon-fe/src/layout/root-layout.jsx
  kickon-fe/src/mocks/rankings.js
Labels: :sparkles: feature

#12 Fix: 루트 레이아웃 섹션명 변경
  kickon-fe/src/layout/root-layout.jsx
Labels: :bug: bug

#14 Feat: 레이아웃 설정
  kickon-fe/.gitignore
  kickon-fe/package.json
  kickon-fe/src/App.jsx
  kickon-fe/src/apis/axios-instance.js
  kickon-fe/src/components/Footer/footer.jsx
  kickon-fe/src/components/Footer/footer.style.js
  kickon-fe/src/hooks/use-custom-fetch.js
  kickon-fe/src/index.css
  kickon-fe/src/layout/root-layout.jsx
  kickon-fe/src/pages/Community/community.jsx
  kickon-fe/src/pages/Home/home.jsx
  kickon-fe/src/pages/News/news.jsx
  kickon-fe/yarn.lock
Labels: :sparkles: feature

#16 Fix: app.jsx 수정
  kickon-fe/src/App.jsx
  kickon-fe/src/pages/Community/community.jsx
  kickon-fe/src/pages/Community/community.style.js
  kickon-fe/src/pages/not-found.jsx
Labels: :bug: bug

#15 Refactor: Footer 로고, 글자 위치 수정
  kickon-fe/src/components/Footer/footer.jsx
  kickon-fe/src/components/Footer/footer.style.js
Labels: :recycle: refactor

#20 Feat: 간편 로그인 모달 생성
  kickon-fe/package-lock.json
  kickon-fe/package.json
  kickon-fe/src/App.jsx
  kickon-fe/src/assets/kakao.svg
  kickon-fe/src/assets/login_logo.svg
  kickon-fe/src/assets/logo_image_redblack.svg
  kickon-fe/src/assets/logo_text_black.png
  kickon-fe/src/assets/naver.svg
  kickon-fe/src/components/Footer/footer.jsx
  kickon-fe/src/components/LoginModal/loginModal.jsx
  kickon-fe/src/components/LoginModal/loginModal.style.js
  kickon-fe/src/components/Profile/profile.jsx
  kickon-fe/src/features/modal/modalSlice.js
  kickon-fe/src/store/store.js
  kickon-fe/yarn.lock
Labels: :sparkles: feature

#22 Feat: 승부예측 컴포넌트 초안 생성
  kickon-fe/src/assets/chevron_down.svg
  kickon-fe/src/assets/chevron_down_non.svg
  kickon-fe/src/assets/chevron_up.svg
  kickon-fe/src/components/MatchCard/matchCard.jsx
  kickon-fe/src/components/MatchCard/matchCard.style.js
  kickon-fe/src/pages/Home/home.jsx
  kickon-fe/yarn.lock
Labels: :sparkles: feature

#29 Feat: 회원가입 화면
  kickon-fe/package-lock.json
  kickon-fe/package.json
  kickon-fe/src/App.jsx
  kickon-fe/src/assets/logo_black.svg
  kickon-fe/src/assets/logo_text_white.svg
  kickon-fe/src/assets/logo_white.svg
  kickon-fe/src/assets/sample_img.png
  kickon-fe/src/components/Footer/footer.jsx
  kickon-fe/src/components/Footer/footer.style.js
  kickon-fe/src/components/Header/header.jsx
  kickon-fe/src/components/Header/header.style.js
  kickon-fe/src/components/Profile/profile.jsx
  kickon-fe/src/components/RankingTable/rankingTable.jsx
  kickon-fe/src/hooks/useCustomFetch.js
  kickon-fe/src/hooks/useForm.js
  kickon-fe/src/layout/root-layout.jsx
  kickon-fe/src/mocks/league.js
  kickon-fe/src/pages/Signup/signup.jsx
  kickon-fe/src/pages/Signup/signup.style.js
  kickon-fe/src/utils/validate.js
Labels: :sparkles: feature
